### ISSUE TITLE
The "ANSI Aware" file type does not appear in Settings > File Types (RubyMine)

### ISSUE THREAD

**Issue by SeinopSys** [alayouni/ansi-highlighter#1]
I just installed the plugin using the provided jar file into RubyMine 2017.1.3, and the "ANSI Aware" file type does not appear in the list. Is the plugin incompatible with this version?

**Comment by alayouni** [comment]
Sorry for the delay, unfortunately I'm only supporting IntelliJ at the moment. I might add support to other JetBrains products depending on how much effort it takes.
Expect to hear from me by end of June.

**Comment by alayouni** [comment]
Fixed with release 1.2.1, now publicly available on all products starting version 2016.3 (build 163+).

commit [8d17611](https://github.com/alayouni/ansi-highlighter/commit/8d176119a57c6dd86e909f2de0ec1bca13825000)

I'm closing the issue, thanks for reporting!
